AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an IAM role for Cribl Cloud Search and Stream
Parameters:
  CriblCloudTrustExternalId:
    Description: Optional External ID for the trust between Cribl Cloud and your AWS Account.
    Type: String
    Default: '123456' 
  CriblSearchCloudTrust:
    Description: Cribl Cloud Trust ARN (This can be found in the Cribl.Cloud site under Trust).
    Type: String
    Default: 'arn:aws:iam::967222283188:role/search-exec-main' 
  CriblStreamCloudTrust:
    Description: Cribl Cloud Trust ARN (This can be found in the Cribl.Cloud site under Trust). 
    Type: String
    Default: 'arn:aws:iam::967222283188:role/main-default'
Resources:
  s3DefaultSecurityLake:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: Cribl Stream Security Lake S3 Bucket for Testing Purposes
  s3DefaultSIEM:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: Cribl Stream SIEM S3 Bucket for Testing Purposes
  CriblTrustCloud:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CriblSearchCloudTrust
                - !Ref CriblStreamCloudTrust
            Action: 
                - 'sts:AssumeRole'
                - 'sts:TagSession'
                - 'sts:SetSourceIdentity'
            Condition:
              StringEquals:
               'sts:ExternalId': !Ref CriblCloudTrustExternalId
      Description: Role to provide access AWS resources from Cribl Cloud Trust
      Policies:
        - PolicyName: S3EmbeddedInlinePolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:ListBucket'
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:GetBucketLocation'
                Resource:
                  - !Sub ${s3DefaultSecurityLake.Arn}
                  - !Sub ${s3DefaultSecurityLake.Arn}/*
                  - !Sub ${s3DefaultSIEM.Arn}
                  - !Sub ${s3DefaultSIEM.Arn}/*                  
Outputs:
  SecurityLakeBucket:
    Description: Amazon S3 Bucket for Testing Amazon Security Lake Destination
    Value: !GetAtt s3DefaultSecurityLake.Arn
  SIEMBucket:
    Description: Amazon S3 Bucket for Testing SIEM Destination
    Value: !GetAtt s3DefaultSIEM.Arn
  RoleName:
    Description: Name of created IAM Role
    Value: !Ref CriblTrustCloud
  RoleArn:
    Description: Arn of created Role
    Value: !GetAtt CriblTrustCloud.Arn
  ExternalId:
    Description: External Id for authentication
    Value: !Ref CriblCloudTrustExternalId