AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an IAM role for Cribl Cloud Search and Stream to access an existing CloudTrail S3 bucket
Parameters:
  CloudTrailsS3:
    Description: Existing AWS S3 bucket for CloudTrail Logs. You can use the aws cli command 'aws_cli % aws cloudtrail describe-trails | grep LogDestination' and select the S3 bucket. 
    Type: String
    Default: ''
  CTSQS:
    Description: Name of the SQS queue for CloudTrail to trigger for S3 log retrieval.
    Type: String
    Default: cribl-cloudtrail-sqs
  CriblCloudAccountID:
    Description: Cribl Cloud Trust AWS Account ID. Navigate to Cribl.Cloud, go to Workspace and click on Access. Find the Trust and copy the AWS Account ID found in the trust ARN.
    Type: String
    Default: '012345678910'
Resources:
  CriblCTQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Ref CTSQS
  CriblCTQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: 
              Service: s3.amazonaws.com
            Action:
              - SQS:SendMessage
            Resource: !GetAtt CriblCTQueue.Arn
            Condition:
              StringEquals:
                'aws:SourceAccount':
                  - !Ref AWS::AccountId
      Queues:
        - !Ref CTSQS
  CriblTrustCloud:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${CriblCloudAccountID}:role/search-exec-main'
                - !Sub 'arn:aws:iam::${CriblCloudAccountID}:role/main-default'
            Action: 
                - 'sts:AssumeRole'
                - 'sts:TagSession'
                - 'sts:SetSourceIdentity'
            Condition:
              StringEquals:
                'sts:ExternalId': !Select 
                  - 4
                  - !Split 
                    - '-'
                    - !Select 
                      - 2
                      - !Split 
                        - '/'
                        - !Ref 'AWS::StackId'
      Description: Role to provide access AWS resources from Cribl Cloud Trust
      Policies:
        - PolicyName: S3EmbeddedInlinePolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:ListBucket'
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:GetBucketLocation'
                Resource:
                  - !Sub "arn:aws:s3:::${CloudTrailsS3}"
                  - !Sub "arn:aws:s3:::${CloudTrailsS3}/*"             
              - Effect: Allow
                Action: 
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:ChangeMessageVisibility
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                Resource: 
                  - !GetAtt CriblCTQueue.Arn
Outputs:
  CloudTrailsS3:
    Description: CloudTrail S3 bucket
    Value: !Ref CloudTrailsS3
  CTSQS:
    Description: SQS Queue for CloudTrail Logs
    Value: !GetAtt CriblCTQueue.Arn
  RoleName:
    Description: Name of created IAM Role
    Value: !Ref CriblTrustCloud
  RoleArn:
    Description: Arn of created Role
    Value: !GetAtt CriblTrustCloud.Arn
  ExternalId:
    Description: External Id for authentication
    Value: !Select 
      - 4
      - !Split 
        - '-'
        - !Select 
          - 2
          - !Split 
            - '/'
            - !Ref 'AWS::StackId'