AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an IAM role for Cribl Cloud Search and Stream
Parameters:
  CriblCloudAccountID:
    Description: Cribl Cloud Trust AWS Account ID
    Type: String
    Default: '012345678910'
Resources:
  CriblTrustCloud:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${CriblCloudAccountID}:role/search-exec-main'
                - !Sub 'arn:aws:iam::${CriblCloudAccountID}:role/main-default'
            Action: 
                - 'sts:AssumeRole'
                - 'sts:TagSession'
                - 'sts:SetSourceIdentity'
            Condition:
              StringEquals:
                'sts:ExternalId': !Select 
                  - 4
                  - !Split 
                    - '-'
                    - !Select 
                      - 2
                      - !Split 
                        - '/'
                        - !Ref 'AWS::StackId'
# Note that the s3:PutObject and sqs:DeleteMessage actions have been commented out due to requirements by AWS to adhere to their policies: 
# https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources.html 
# https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html 
# https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonsqs.html 
# Make sure to update the Resources to include only the S3 buckets that you want to grant access to Cribl Cloud to read or write. 
      Description: Role to provide access AWS resources from Cribl Cloud Trust
      Policies:
        - PolicyName: CriblCloudS3SQSPolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:ListBucket'
                  - 's3:GetObject'
                  #- 's3:PutObject'
                  - 's3:GetBucketLocation'
                Resource: '*'
              - Effect: Allow
                Action: 
                  - sqs:ReceiveMessage
                  #- sqs:DeleteMessage
                  #- sqs:ChangeMessageVisibility
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                Resource: '*'
              - Effect: Allow
                Action: 
                  - ec2:DescribeInstances
                  - ec2:DescribeVolumes
                  - ec2:DescribeSecurityGroups
                Resource: '*'
              - Effect: Allow
                Action: 
                  - lambda:ListFunctions
                Resource: '*'
              - Effect: Allow
                Action: 
                  - iam:ListRoles
                  - iam:ListUsers
                  - iam:ListGroups
                  - iam:ListPolicies
                  - iam:ListMFADevices
                Resource: '*'
              - Effect: Allow
                Action: 
                  - cloudformation:ListExports
                  - cloudformation:ListStacks
                  - cloudformation:ListStackSets
                Resource: '*'
              - Effect: Allow
                Action: 
                  - dynamodb:ListBackups
                Resource: '*'
              - Effect: Allow
                Action: 
                  - dynamodb:ListTables
                Resource: '*'
              - Effect: Allow
                Action: 
                  - rds:DescribeDBInstances
                  - rds:DescribeDBClusterEndpoints
                  - rds:DescribeDBSecurityGroups
                  - rds:DescribeCertificates
                  - rds:DescribeDBClusters
              - Effect: Allow
                Action: 
                  - cloudtrail:LookupEvents
                Resource: '*'
              - Effect: Allow
                Action: 
                  - elasticfilesystem:DescribeFileSystems 
                Resource: '*'
Outputs:
  RoleName:
    Description: Name of created IAM Role
    Value: !Ref CriblTrustCloud
  RoleArn:
    Description: Arn of created Role
    Value: !GetAtt CriblTrustCloud.Arn
  ExternalId:
    Description: External Id for authentication
    Value: !Select 
      - 4
      - !Split 
        - '-'
        - !Select 
          - 2
          - !Split 
            - '/'
            - !Ref 'AWS::StackId'