AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an IAM Role that trusts Cribl Cloud and creates cloudtrail and VPC flow logging to an S3 bucket. 
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W9001
        - W9002
        - W9003
        - W3005
Parameters:
  CriblCloudAccountID:
    Description: Cribl Cloud Trust AWS Account ID. Navigate to Cribl.Cloud, go to Workspace and click on Access. Find the Trust and copy the AWS Account ID found in the trust ARN.
    Type: String
    Default: '012345678910'
  CTSQS:
    Description: Name of the SQS queue for CloudTrail to trigger for S3 log retrieval.
    Type: String
    Default: cribl-cloudtrail-sqs
  TrafficType:
    Description: The type of traffic to log.
    Type: String
    Default: ALL
    AllowedValues:
      - ACCEPT
      - REJECT
      - ALL
  VPCSQS:
    Description: Name of the SQS for VPCFlow Logs.
    Type: String
    Default: cribl-vpc-sqs
  VPCId:
    Description: Select your VPC to enable logging
    Type: AWS::EC2::VPC::Id
Resources:
  CriblCTQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Ref CTSQS
  CriblCTQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: 
              Service: s3.amazonaws.com
            Action:
              - SQS:SendMessage
            Resource: !GetAtt CriblCTQueue.Arn
            Condition:
              StringEquals:
                'aws:SourceAccount':
                  - !Ref AWS::AccountId
      Queues:
        - !Ref CTSQS
  TrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        QueueConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Queue: !GetAtt CriblCTQueue.Arn
    DependsOn: CriblCTQueuePolicy
  TrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSLogDeliveryWrite
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: 's3:PutObject'
            Resource:  
              - !Sub '${TrailBucket.Arn}/AWSLogs/'
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
          - Sid: 'AWSCloudTrailAclCheck'
            Effect: 'Allow'
            Principal: 
              Service: 'cloudtrail.amazonaws.com'
            Action: 's3:GetBucketAcl'
            Resource: !Sub '${TrailBucket.Arn}'
          - Sid: 'AWSCloudTrailWrite'
            Effect: 'Allow'
            Principal: 
              Service: 'cloudtrail.amazonaws.com'
            Action: 's3:PutObject'
            Resource: !Sub '${TrailBucket.Arn}/AWSLogs/*/*'
            Condition:
              StringEquals:
                's3:x-amz-acl': 'bucket-owner-full-control'
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt TrailBucket.Arn
              - !Sub '${TrailBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false
  ExternalTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn:
      - TrailBucket
      - TrailBucketPolicy
    Properties:
      S3BucketName: !Ref TrailBucket
      #S3KeyPrefix: AWSLogs
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      TrailName: !Sub '${TrailBucket}-trail'
  CriblVPCQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Ref VPCSQS
  CriblVPCQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - 'SQS:SendMessage'
            Resource: !GetAtt CriblVPCQueue.Arn
            Condition:
              StringEquals:
                'aws:SourceAccount':
                  - !Ref "AWS::AccountId"
      Queues:
        - !Ref VPCSQS
  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      NotificationConfiguration:
        QueueConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Queue: !GetAtt CriblVPCQueue.Arn
    DependsOn: CriblVPCQueuePolicy
  FlowLog:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      LogDestination: !Sub 'arn:${AWS::Partition}:s3:::${LogBucket}'
      LogDestinationType: s3
      ResourceId: !Ref VPCId
      ResourceType: VPC
      TrafficType: !Ref TrafficType
  CriblTrustCloud:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${CriblCloudAccountID}:role/search-exec-main'
                - !Sub 'arn:aws:iam::${CriblCloudAccountID}:role/main-default'
            Action: 
                - 'sts:AssumeRole'
                - 'sts:TagSession'
                - 'sts:SetSourceIdentity'
            Condition:
              StringEquals:
                'sts:ExternalId': !Select 
                  - 4
                  - !Split 
                    - '-'
                    - !Select 
                      - 2
                      - !Split 
                        - '/'
                        - !Ref 'AWS::StackId'
      Description: Role to provide access AWS resources from Cribl Cloud Trust
      Policies:
        - PolicyName: SQS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                Resource:
                  - !GetAtt CriblCTQueue.Arn
                  - !GetAtt CriblVPCQueue.Arn
        - PolicyName: S3EmbeddedInlinePolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 's3:ListBucket'
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:GetBucketLocation'
                Resource:
                  - !Sub ${TrailBucket.Arn}
                  - !Sub ${TrailBucket.Arn}/*
                  - !Sub ${LogBucket.Arn}
                  - !Sub ${LogBucket.Arn}/*                  
Outputs:
  CloudTrailS3Bucket:
    Description: Amazon S3 Bucket for CloudTrail Events
    Value: !GetAtt TrailBucket.Arn
  VPCFlowLogsS3Bucket:
    Description: Amazon S3 Bucket for VPC Flow Logs
    Value: !GetAtt LogBucket.Arn
  RoleName:
    Description: Name of created IAM Role
    Value: !Ref CriblTrustCloud
  RoleArn:
    Description: Arn of created Role
    Value: !GetAtt CriblTrustCloud.Arn
  ExternalId:
    Description: External Id for authentication
    Value: !Select 
      - 4
      - !Split 
        - '-'
        - !Select 
          - 2
          - !Split 
            - '/'
            - !Ref 'AWS::StackId'